### ISSUE TITLE
applied for toolbench_key but no one responded

### ISSUE THREAD

**Issue by stanpcf** [THUNLP-MT/StableToolBench#13]
about two weeks, my email is: pcf@bjtu.edu.cn

**Comment by zhichengg** [comment]
I have directed your message to Shihao Liang (shihaoliang0828@gmail.com) who is in charge of the key system from the ToolBench team. If you need any more help, please don't hesitate to get in touch with him.

**Comment by stanpcf** [comment]
thanks very much
