### ISSUE TITLE
Did ToolBench server crashed?

### ISSUE THREAD

**Issue by Reason-Wang** [THUNLP-MT/StableToolBench#18]
First thanks for your amazing work in tool evaluation! I was able to use StableToolBench one week ago. However, I can't get the response from the server now, returning the following error. Is this because the server crashed?

```bash
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='8.218.239.54', port=8080): Max retries exceeded with url: /rapidapi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5f7d9a9cf0>, 'Connection to 8.218.239.54 timed out. (connect timeout=None)'))
```

**Comment by kingb12** [comment]
It looks like the ToolBench maintainers moved the service url, you'll need to update it in `config.yml`:

https://github.com/OpenBMB/ToolBench/commit/6a0af3f48e31aed9a4a1ac3143f38d2e7cdd909a
